<a href="https://colab.research.google.com/github/mearoche/text-mining-tutorial/blob/master/Ass3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0. Data import and preparation/clean up

### Set up

In [1]:
# For Colab: 
# 1. First CHANGE RUNTIME TYPE to GPU 
# 2. Then run install commands commented out below
# 3. Then RESTART RUNTIME
# 4. Then run git clone command commented out below
# 5. Then run all the other cells

In [2]:
# Install necessary packages
#!pip install --upgrade jax==0.2.3 jaxlib==0.1.56+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
#!pip install --upgrade numpyro==0.4.1
#!pip install flashtext
#!pip install contractions
#!pip install lda
#!pip install --upgrade spacy==2.2.4
#!pip install --upgrade folium==0.2.1
#!pip install topic-modelling-tools

In [3]:
# Restart RUNTIME after installing packages!

In [4]:
# Cloning GitHub (to do only once! Then comment it)
!git clone https://mearoche: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@github.com/mearoche/text-mining-tutorial.git

fatal: destination path 'text-mining-tutorial' already exists and is not an empty directory.


In [5]:
cd text-mining-tutorial

/content/text-mining-tutorial


In [6]:
# Check that the directory contains the growthdata.csv file
!ls

Ass3.ipynb	final_output_agg.csv	topic_description.csv
df_ranking.csv	README.md		tt.csv
dict.csv	requirements.txt	tutorial_notebook.ipynb
dt.csv		speech_data_extend.txt	tutorial.py
dt_query.csv	tfidf_ranking.csv


In [7]:
# Install necessary packages

# JAX
import jax
from jax import random, vmap, jit
import jax.numpy as jnp
import jax.nn as nn
from jax.random import PRNGKey as Key

# Panda
import pandas as pd

# Numpyro
import numpyro
numpyro.set_platform("cpu")
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS, log_likelihood
import numpyro.infer.util 
from numpyro.primitives import deterministic
from numpyro.handlers import condition, substitute, block

# Matplot
import matplotlib.pyplot as plt
import seaborn as sns

# Spacy
import spacy
spacy.load('en_core_web_sm')

# LDA
import lda

# Others
import time
import string
import topicmodels
from sklearn.preprocessing import StandardScaler
import sys
sys.path.append('../pymodules')

### Import data

In [8]:
# Import US Presidential State-of-the-Union addresses from 1945 onwards
data = pd.read_table("speech_data_extend.txt", encoding="utf-8")
data = data[data.year >= 1945]

In [9]:
# Check the number of documents in the dataset
len(data)

10260

## 1. LDA

### Pre-processing

In [10]:
# I define docsobj, tokenized
docsobj = topicmodels.RawDocs(data.speech, "long")

In [11]:
# Check the stop words list, from http://snowball.tartarus.org/algorithms/english/stop.txt (long version)
docsobj.stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'also',
 'am',
 'an',
 'and',
 'another',
 'any',
 'are',
 'as',
 'at',
 'back',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'could',
 'did',
 'do',
 'does',
 'doing',
 'down',
 'during',
 'each',
 'even',
 'ever',
 'every',
 'few',
 'first',
 'five',
 'for',
 'four',
 'from',
 'further',
 'get',
 'go',
 'goes',
 'had',
 'has',
 'have',
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'high',
 'him',
 'himself',
 'his',
 'how',
 'however',
 'i',
 'if',
 'in',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'least',
 'less',
 'like',
 'long',
 'made',
 'make',
 'many',
 'me',
 'more',
 'most',
 'my',
 'myself',
 'never',
 'new',
 'no',
 'nor',
 'not',
 'now',
 'of',
 'off',
 'old',
 'on',
 'once',
 'one',
 'only',
 'or',
 'other',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'put',
 'said',
 'same',
 'say',
 'says',
 'second',
 'see',
 

In [12]:
# Since we want to focus on words and not tokens, I will clean the tokens (all non-alphabetic and numeric tokens), and remove those with length less than 1
docsobj.token_clean(1)

In [13]:
# I remove the stopwords from docsobj.tokens
docsobj.stopword_remove("tokens")

In [14]:
# I want to group together words that are grammatically different but thematically identical, i.e. stemming, using Porter stemmer
docsobj.stem()
docsobj.stopword_remove("stems") # I again remove stopwords as stemmed forms of tokens may be in the stopword list

In [15]:
# I use TF-IDF on each stem to measure informativeness (to identify common words and rare words)
docsobj.term_rank("stems") # Outcome is 2 csv files: df_ranking.csv ranks each stem according to its document frequency, and tfidf_ranking.csv ranks each stem according to the tf-idf measure.

In [16]:
# Plotting the ranking of the TF-IDF to explore a potential cutoff value
plt.plot([x[1] for x in docsobj.tfidf_ranking])

I take as cutoff 5,000. It seems reasonable according to the above plot.

In [17]:
# I now drop the stems below this cutoff
cutoff = 5000
docsobj.rank_remove("tfidf","stems",docsobj.tfidf_ranking[cutoff][1])
all_stems = [s for d in docsobj.stems for s in d]

In [18]:
# I check number of unique stems
print(len(set(all_stems)))
V = len(set(all_stems))
# Check number of total stems
print(len(all_stems))

4918
268763


I obtain 4,918 unique stems and 268,763 total stems. I can now estimate my LDA.

### Estimations

I will estimate an LDA on individual paragraphs using the collapsed Gibbs sampling algorithm of Griffiths and Steyvers (2004).

In [19]:
# I choose the number of topics (arbitrary choice)
topics = 20
ldaobj = topicmodels.LDA.LDAGibbs(docsobj.stems,topics)

In [20]:
# I choose the hyperparameters of the Dirichlet priors, here I follow Griffiths and Steyvers (2004)
print(ldaobj.K) # number of topic, arbitrary, here K = 20
print(ldaobj.alpha) # hyperparameter for document-topic distribution, automatically defined as 50/K, with K the number of topics
print(50/topics) # checked and all good
print(ldaobj.beta) # hyperparameter for topics, automatically defined as 200/V, with V the number of unique vocabulary elements
print(200/V) # checked and all good

20
2.5
2.5
0.040666937779585195
0.040666937779585195


Now, I will sample.

To do so, I have to decide on three parameters:


1.   Number of iterations I want the chain to burn in before beginning to sample (A)
2.   Thinning interval: the number of iterations to let the chain run between samples (B)
3.   Number of samples to take (C)

Total number of iterations = A + B x C



In [21]:
# I select arbitrary values for A, B, and C keeping in mind that I do not want the code to take too long to run
A = 0 
B = 50
C = 10
ldaobj.sample(A,B,C) # Here 500 iterations
ldaobj.perplexity() # To check goodness-of-fit of each of the C samples (the lower the value the better the fit)

Iteration 10 of (collapsed) Gibbs sampling
Iteration 20 of (collapsed) Gibbs sampling
Iteration 30 of (collapsed) Gibbs sampling
Iteration 40 of (collapsed) Gibbs sampling
Iteration 50 of (collapsed) Gibbs sampling
Iteration 60 of (collapsed) Gibbs sampling
Iteration 70 of (collapsed) Gibbs sampling
Iteration 80 of (collapsed) Gibbs sampling
Iteration 90 of (collapsed) Gibbs sampling
Iteration 100 of (collapsed) Gibbs sampling
Iteration 110 of (collapsed) Gibbs sampling
Iteration 120 of (collapsed) Gibbs sampling
Iteration 130 of (collapsed) Gibbs sampling
Iteration 140 of (collapsed) Gibbs sampling
Iteration 150 of (collapsed) Gibbs sampling
Iteration 160 of (collapsed) Gibbs sampling
Iteration 170 of (collapsed) Gibbs sampling
Iteration 180 of (collapsed) Gibbs sampling
Iteration 190 of (collapsed) Gibbs sampling
Iteration 200 of (collapsed) Gibbs sampling
Iteration 210 of (collapsed) Gibbs sampling
Iteration 220 of (collapsed) Gibbs sampling
Iteration 230 of (collapsed) Gibbs sampli

array([1009.46652843,  967.89350487,  952.0836386 ,  946.38175273,
        941.13131817,  936.55006113,  931.91043021,  931.66580854,
        928.94076661,  928.05112509])

Here it would be preferable to use a convergence criterion to decide when to stop the sampling based on a minimized perplexity, for example stopping when the perplexity does not improve by more than 10^-2.

However, this would require a lot of computational power. I only have time limited use of GPU on Colab, therefore I opted for not using a convergence criterion for the purpose of this assignment.

In [22]:
# Keeping the last n samples (as they are the ones with the lowest perplexity, n is arbitrary)
n = 4
ldaobj.samples_keep(n)

One should normally take as many samples as computationally feasible but given my low computational power, I choose $n$ arbitrarily to be small.

In [23]:
# Let us look at the shape:
    # of my estimated topics
print(ldaobj.tt.shape)
# All good, it matches my number of unique stems, topics, and samples
    # of my estimated document-topic distributions
print(ldaobj.dt.shape)
# All good, it matches my number of documents, topics, and samples

(4918, 20, 4)
(10260, 20, 4)


In [24]:
# Now I will extract a csv file containing the first m stems in each topic ranked according to their probability, using the final stored sample
m = 20 # chosen arbitrarily 
ldaobj.topic_content(m)

I have checked the topics and they seem reasonable, for example:

- Topic 0: govern, feder, state, respons, local, public

- Topic 6: world, peac, free, freedom, secur, america, fight, threat, danger

- Topic 8: health, system, care, secur, need, social, servic

- Topic 16: war, forc, defens, militari, soviet, power, nuclear, arm

## 2. Ranking topics according to whether they are more Democrat or Republican

First, I use querying to bring the analysis from paragraph level to speech level (one speech per year), obtaining speech level distributions.

In [25]:
# Estimated distribution of the m topics (m columns) within each document (each row)
dt = ldaobj.dt_avg() # suming each row = 1

## This gives in each cell the proportion that a topic represents in each document

In [26]:
# Estimated distribution of the m topics (m columns) within each stems (each row)
tt = ldaobj.tt_avg() # suming each column = 1
ldaobj.dict_print()

## This gives in each cell the associative power of a stem to a given topic

In [27]:
# Building my final dataset at speech level
data['speech'] = [' '.join(s) for s in docsobj.stems] # I replace the speech field in the original data with its cleaned version from docsobj (after the processing done previously)
aggspeeches = data.groupby(['year','president'])['speech'].apply(lambda x: ' '.join(x)) # I aggregate up to the speech level
aggdocs = topicmodels.RawDocs(aggspeeches) # create new RawDocs object that contains entire speech stems in aggdocs.tokens
queryobj = topicmodels.LDA.QueryGibbs(aggdocs.tokens,ldaobj.token_key,ldaobj.tt) # initialize query object with ldaobj attributes
queryobj.query(10) # I query the selected samples (querying does not require a lot of iterations to obtain good perplexity, so 10 is chosen arbitrarily)
dt_query = queryobj.dt_avg()
aggdata = pd.DataFrame(dt_query,index=aggspeeches.index,columns=['T' + str(i) for i in range(queryobj.K)]) # Aggregating
aggdata.to_csv("final_output_agg.csv") # Obtaining final dataset

Sample 0 queried
Sample 1 queried
Sample 2 queried
Sample 3 queried


I now have in "final_output_agg.cv" a row per speech and a column per topic. For each speech the row sums to 1 across all topics.


In [28]:
# I use the csv file created
final_data = pd.read_csv("final_output_agg.csv")
final_data # Checking the data

year    president        T0        T1        T2        T3        T4  \
0   1945  RooseveltII  0.034142  0.065556  0.037015  0.047146  0.060345   
1   1946       Truman  0.013798  0.067971  0.052615  0.031454  0.029247   
2   1947       Truman  0.021375  0.093782  0.065225  0.036330  0.041399   
3   1948       Truman  0.039511  0.076395  0.055275  0.073767  0.044361   
4   1949       Truman  0.033996  0.085511  0.045576  0.048397  0.046318   
..   ...          ...       ...       ...       ...       ...       ...   
68  2010        Obama  0.082973  0.024291  0.017582  0.026064  0.080429   
69  2011        Obama  0.087751  0.019345  0.019180  0.026753  0.098041   
70  2012        Obama  0.092289  0.015562  0.015872  0.020285  0.091824   
71  2013        Obama  0.072375  0.027501  0.013166  0.029215  0.084216   
72  2014        Obama  0.084764  0.016486  0.026272  0.032746  0.092517   

          T5        T6        T7  ...       T10       T11       T12       T13  \
0   0.036236  0.041837  0.081190  ...  0.028395  0.016706  0.063121  0.039207   
1   0.053468  0.009941  0.039726  ...  0.035349  0.013798  0.027689  0.062092   
2   0.042920  0.021713  0.049510  ...  0.033119  0.020193  0.052974  0.072153   
3   0.069018  0.016269  0.037995  ...  0.051031  0.029002  0.094078  0.055174   
4   0.066954  0.022120  0.027613  ...  0.061461  0.035481  0.071853  0.081799   
..       ...       ...       ...  ...       ...       ...       ...       ...   
68  0.080429  0.099553  0.032465  ...  0.028223  0.062384  0.029766  0.094849   
69  0.049144  0.100757  0.031116  ...  0.053836  0.104215  0.030128  0.081906   
70  0.066971  0.085708  0.034221  ...  0.053422  0.085553  0.025240  0.102121   
71  0.069336  0.088423  0.035213  ...  0.042537  0.099096  0.027423  0.084294   
72  0.067450  0.108326  0.036360  ...  0.035080  0.105465  0.033047  0.087775   

         T14       T15       T16       T17       T18       T19  
0   0.130041  0.042665  0.116404  0.026787  0.015780  0.067407  
1   0.053746  0.239726  0.033030  0.024091  0.050723  0.041395  
2   0.049003  0.068351  0.045792  0.066070  0.033119  0.062437  
3   0.052648  0.081144  0.015663  0.039915  0.052041  0.054568  
4   0.041865  0.084175  0.023456  0.055671  0.029246  0.046764  
..       ...       ...       ...       ...       ...       ...  
68  0.057912  0.017967  0.031462  0.071869  0.063849  0.059223  
69  0.072358  0.012183  0.035891  0.046674  0.056059  0.031610  
70  0.054816  0.015717  0.039486  0.061861  0.060390  0.031744  
71  0.045185  0.014724  0.048613  0.077984  0.063104  0.032097  
72  0.046296  0.014679  0.053448  0.046748  0.042758  0.025595  

[73 rows x 22 columns]

I use the respective partisanship of each president in the sample: Truman (D), Eisenhower (R), Kennedy (D), Johnson (D), Nixon (R), Ford (R), Carter (D), Reagan (R), Bush Senior (R), Clinton (D), Bush Jr (R), and Obama (D). 

I create a dummy for being Republican (=1) or not (=0). Calculating the correlation between this dummy and the topics allows me to rank topics as either Democrat (if the correlation is negative) or Republican (if the correlation is positive). I also obtain a scale from -1 (most Democrat) to 1 (most Republican) on which I can rank each topic according to the obtained correlation.

To note: I can proceed this way as the sample is well balanced with 50.7% of speeches coming from Republican presidents and 49.3% from Democrat presidents.

In [45]:
original_data = final_data.copy()
topics = original_data.columns[2:-1]
### TO DELETE LATER

In [37]:
final_data["rep"] = 0

republicans = ["Eisenhower", "Nixon", "Ford", "Reagan", "BushI", "BushII"]
final_data["rep"] = final_data.apply(
    lambda x: 1 if x["president"] in republicans else 0, axis=1
)

In [62]:
final_data[["president","T0","rep"]][final_data.president=="Nixon"]

president        T0  rep
27     Nixon  0.112494    1
28     Nixon  0.112936    1
29     Nixon  0.054174    1
30     Nixon  0.044103    1
31     Nixon  0.031835    1

In [53]:
topics_correlations = pd.DataFrame(topics, columns=["topics"])
topics_correlations["corr"] = 0
for topic in topics_correlations.topics.unique(): 
  topics_correlations.loc[topics_correlations["topics"]==topic, "corr"] = final_data[[topic,"rep"]].corr().iloc[0,1]
  

In [63]:
topics_correlations

topics      corr
0      T0  0.169126
1      T1 -0.009210
2      T2  0.108119
3      T3  0.061331
4      T4 -0.252839
5      T5 -0.208727
6      T6  0.063043
7      T7 -0.201684
8      T8  0.031128
9      T9  0.248970
10    T10  0.094113
11    T11 -0.226358
12    T12  0.138913
13    T13 -0.357420
14    T14 -0.147613
15    T15 -0.108803
16    T16  0.240547
17    T17 -0.305713
18    T18  0.196664
19    T19  0.193681

In [29]:
# SHOW A GRAPH OF THE SCALE AS AN AXIS FROM -1 to 1 WITH THE TOPICS

## 3. Ranking presidents on the basis of D-R scale

In [64]:
# create dummy in topics_correlations for republican/democrat

topics_correlations["topic_ideology"] = topics_correlations["corr"].copy()
topics_correlations["topic_ideology"] = topics_correlations["topic_ideology"].apply(
    lambda x: -1 if x < 0 else 1
)


In [65]:
topics_correlations

topics      corr  topic_ideology
0      T0  0.169126               1
1      T1 -0.009210              -1
2      T2  0.108119               1
3      T3  0.061331               1
4      T4 -0.252839              -1
5      T5 -0.208727              -1
6      T6  0.063043               1
7      T7 -0.201684              -1
8      T8  0.031128               1
9      T9  0.248970               1
10    T10  0.094113               1
11    T11 -0.226358              -1
12    T12  0.138913               1
13    T13 -0.357420              -1
14    T14 -0.147613              -1
15    T15 -0.108803              -1
16    T16  0.240547               1
17    T17 -0.305713              -1
18    T18  0.196664               1
19    T19  0.193681               1

In [93]:
topics

Index(['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10',
       'T11', 'T12', 'T13', 'T14', 'T15', 'T16', 'T17', 'T18', 'T19'],
      dtype='object')

In [109]:
import numpy as np
topic_ideology_r = topics_correlations.topic_ideology.values

df = final_data[["year","president"]].drop_duplicates()
df["grade"] = 0

for index, row in final_data.iterrows():
  t = np.array(row[topics].values)
  if row["rep"] == 1:
    j = 1
    
  else:
    j = -1
  
  grade = (topic_ideology_r*j).T@t * j

  df.iloc[index,2] = grade

df_collapse = df.pivot_table(values=["grade"], index=["president"], aggfunc="mean").reset_index()

df_collapse = df_collapse.sort_values(by=["grade"]).reset_index(drop=True)
df_collapse

president     grade
0         Obama -0.039277
1       Clinton -0.038059
2   RooseveltII  0.002533
3        Truman  0.018765
4     JohnsonII  0.085878
5       Kennedy  0.094612
6        BushII  0.135898
7         BushI  0.155674
8        Carter  0.187006
9    Eisenhower  0.190184
10       Reagan  0.221717
11         Ford  0.229002
12        Nixon  0.257037

In [111]:
df_collapse.plot(x="president",y="grade",kind="scatter", figsize=(12,5))

In [30]:

### THE REST WAS DONE IN STATA BECAUSE I HAVE LOW EXPERIENCE WITH PYTHON.
# SHOW A GRAPH OF THE SCALE AS AN AXIS FROM -1 to 1 WITH THE PRESIDENTS

I weight negatively Democrat topics for Republican presidents and vice versa. Then, I sum across the weighted topics for each speech, obtaining a Republican score (for Republican presidents) and a Democrat score (for Democrat presidents). Since each row sums to 1, the scores are between -1 and 1. I then average the score for each president across all their respective speeches.

I verify that the average scoring makes sense as it should be above zero as one expects Democrat presidents to use more Democrat Topics and vice versa. This is the case in the results I obtain.

Finally, I multiply by -1 the average score for Democrat presidents and collaspe at president level. I obtain a scale from -1 (most Democrat) and 1 (most Republican) on which I rank presidents.